In [5]:
from dataloader import LineMODCocoDataset
import torch
import numpy as np

In [4]:
root = 'test_data_subset'
modelsPath = 'lm_models/models/models_info.json'
annFile = 'LOOKHEREannotations.json'


dataset = LineMODCocoDataset(root, annFile, modelsPath)

loading annotations into memory...
Done (t=0.19s)
creating index...
index created!
{'1': {'diameter': 102.099, 'min_x': -37.9343, 'min_y': -38.7996, 'min_z': -45.8845, 'size_x': 75.8686, 'size_y': 77.5992, 'size_z': 91.769}, '2': {'diameter': 247.506, 'min_x': -107.835, 'min_y': -60.9279, 'min_z': -109.705, 'size_x': 215.67, 'size_y': 121.856, 'size_z': 219.41}, '3': {'diameter': 167.355, 'min_x': -83.2162, 'min_y': -82.6591, 'min_z': -37.2364, 'size_x': 166.432, 'size_y': 165.318, 'size_z': 74.4728, 'symmetries_continuous': [{'axis': [0, 0, 1], 'offset': [0, 0, 0]}]}, '4': {'diameter': 172.492, 'min_x': -68.3297, 'min_y': -71.5151, 'min_z': -50.2485, 'size_x': 136.659, 'size_y': 143.03, 'size_z': 100.497}, '5': {'diameter': 201.404, 'min_x': -50.3958, 'min_y': -90.8979, 'min_z': -96.867, 'size_x': 100.792, 'size_y': 181.796, 'size_z': 193.734}, '6': {'diameter': 154.546, 'min_x': -33.5054, 'min_y': -63.8165, 'min_z': -58.7283, 'size_x': 67.0107, 'size_y': 127.633, 'size_z': 117.457}, 

In [13]:
print(f'v{eval("3")}')

v3


In [15]:
[i for i in np.arange(3)]

[0, 1, 2]

In [19]:
x = np.arange(9).reshape(3, 3)
x, x[:2, :] / x[2, :]

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0.        , 0.14285714, 0.25      ],
        [0.5       , 0.57142857, 0.625     ]]))

In [3]:
len(dataset)

18273

In [4]:
dataset[0][1]

{'id': 1, 'image_id': 1, 'category_id': 1, 'bbox': [244, 150, 43, 57], 'area': 2451, 'iscrowd': 0, 'cam_R_m2c': [0.0963063, 0.99404401, 0.0510079, 0.57332098, -0.0135081, -0.81922001, -0.81365103, 0.10814, -0.57120699], 'cam_t_m2c': [-105.3577515, -117.52119142, 1014.8770132], 'cam_K': [572.4114, 0.0, 325.2611, 0.0, 573.57043, 242.04899, 0.0, 0.0, 1.0]}


tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 